### PR TITLE
Support bluetooth volume

### PR DESCRIPTION
**Pull request by ShayYaari**

### CODE REVIEW

**Comment by ShayYaari** [comment]
@Zlass Can you please review and release a version?

**Review by Zlass — COMMENTED** [review]
The `return 6` is a bit scary to me, but if it works 🤷‍♂️ 

How are we determining the correct volume mode? ie. I'm in a phone call will that adjust the phone volume?

**Comment by ShayYaari** [comment]
@Zlass It should not matter, since if we are using a bluetooth device such as phone clip or an accessory, it does not matter whether we are in a call or listening to music. We just need to change to bluetooth volume bar...
Does it make sense?

**Comment by ShayYaari** [comment]
@Zlass Currently it was tested in some scenarios with 2 Samsung devices. I'll let Chris do more tests with more devices and modes (music / video call / phone call etc.) and see if it is still working.
We may need to add more switch cases to the case where we need to find the right mode type...
WDYT?

**Pull request merged**
